import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ConfirmDialog } from "@/components/ui/ConfirmDialog";
import { MapsConfigProvider } from "@/components/shop/MapsConfig";
import { Toaster } from "@/components/ui/Toaster";
import { DEFAULT_DESCRIPTION, SITE_KEYWORDS, SITE_NAME, SITE_URL } from "@/lib/seo";

// Plus Jakarta Sans for all UI/body text — clean, friendly and highly legible.
// Bricolage Grotesque for display headings + the brand wordmark (characterful).
//
// Self-hosted rather than next/font/google. Both are multi-axis VARIABLE fonts
// (Bricolage has opsz, wdth and wght), and asking next/font/google for a list of
// discrete weights made its loader fail to parse Google's response — the Vercel
// build died with "Cannot read properties of null (reading '1')". It built fine
// locally, which is the tell: it is a build-time network dependency, not a code
// error.
//
// Self-hosting removes that dependency entirely and is better in production
// anyway: no fetch during the build, no request to Google at runtime (so no
// third-party font call from the customer's browser), and one file per family
// covering every weight. Files are the latin subset of the variable font; both
// families are SIL Open Font License, see fonts/OFL.txt.
const jakarta = localFont({
  src: "./fonts/PlusJakartaSans-Variable.woff2",
  variable: "--font-jakarta",
  weight: "200 800", // variable range, not a single weight
  display: "swap",
});
const bricolage = localFont({
  src: "./fonts/BricolageGrotesque-Variable.woff2",
  variable: "--font-bricolage",
  weight: "200 800",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: "Ootybites — Taste of the Hills",
    template: "%s | Ootybites",
  },
  description: DEFAULT_DESCRIPTION,
  keywords: SITE_KEYWORDS,
  applicationName: SITE_NAME,
  authors: [{ name: SITE_NAME }],
  creator: SITE_NAME,
  robots: { index: true, follow: true },
  // app/icon.png is picked up automatically; these add the Apple touch icon and
  // the explicit sizes, all generated by scripts/build-brand.mjs from the real
  // brand artwork.
  icons: {
    icon: [
      { url: "/brand/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/brand/icon-48.png", sizes: "48x48", type: "image/png" },
      { url: "/brand/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    apple: [{ url: "/brand/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    title: "Ootybites — Taste of the Hills",
    description: DEFAULT_DESCRIPTION,
    url: SITE_URL,
    locale: "en_IN",
  },
  twitter: {
    card: "summary_large_image",
    title: "Ootybites — Taste of the Hills",
    description: DEFAULT_DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${jakarta.variable} ${bricolage.variable}`}>
      <body>
        {/* Skip link — first thing in the tab order so keyboard and screen-reader
            users can jump past the header straight to the page content. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-full focus:bg-brand-800 focus:px-5 focus:py-3 focus:text-sm focus:font-semibold focus:text-cream focus:outline-none focus:ring-2 focus:ring-brand-300"
        >
          Skip to content
        </a>
        {/* Read server-side (no NEXT_PUBLIC_ prefix available) and handed to the
            client components that need them. See MapsConfig for why. */}
        <MapsConfigProvider
          apiKey={process.env.GOOGLE_MAPS_API_KEY}
          mapId={process.env.GOOGLE_MAPS_MAP_ID}
        >
          {children}
        </MapsConfigProvider>
        <ConfirmDialog />
        <Toaster />
      </body>
    </html>
  );
}
